<Window x:Class="Wpfs.LayerWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"  
        xmlns:acmgd="clr-namespace:Autodesk.AutoCAD.ApplicationServices;assembly=acmgd"
        Title="图层管理器" Height="350" Width="525">
    <Grid>
        <ListView ItemsSource="{Binding Source={x:Static acmgd:Application.UIBindings}, Path=Collections.Layers}">
            <ListView.View>
                <GridView>
                    <GridViewColumn Header="名称" Width="100">
                        <GridViewColumn.CellTemplate>
                            <DataTemplate>
                                <TextBlock Text="{Binding Path=Name}" HorizontalAlignment="Center"/>
                            </DataTemplate>
                        </GridViewColumn.CellTemplate>
                    </GridViewColumn>
                    <GridViewColumn Header="开" Width="55">
                        <GridViewColumn.CellTemplate>
                            <DataTemplate>
                                <CheckBox  IsChecked="{Binding Path=IsOff}"/>
                            </DataTemplate>
                        </GridViewColumn.CellTemplate>
                    </GridViewColumn>
                    <GridViewColumn Header="冻结" Width="55">
                        <GridViewColumn.CellTemplate>
                            <DataTemplate>
                                <CheckBox  IsChecked="{Binding Path=IsFrozen}"/>
                            </DataTemplate>
                        </GridViewColumn.CellTemplate>
                    </GridViewColumn>
                    <GridViewColumn Header="锁定" Width="55" >
                        <GridViewColumn.CellTemplate>
                            <DataTemplate>
                                <CheckBox  IsChecked="{Binding Path=IsLocked}" />
                            </DataTemplate>
                        </GridViewColumn.CellTemplate>
                    </GridViewColumn>
                </GridView>
            </ListView.View>
        </ListView>
    </Grid>
</Window>
